### ISSUE TITLE
Docker terminated with return code 5.

### ISSUE THREAD

**Issue by lambq** [sciapp/nojava-ipmi-kvm#18]
[INFO] Starting the Docker container...
Error: No such container: nojava-ipmi-kvmrc-94f36d93-faaf-479d-9083-7f793561defe
[INFO] Starting new HTTPS connection (1): 192.168.4.82
[ERROR] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
[ERROR] Docker terminated with return code 5.

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by IngoMeyer441** [comment]
Did you try the

```yaml
allow_insecure_ssl: True
```

configuration option? This should avoid the

```
[ERROR] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

error message.

**Comment by lambq** [comment]
Digest: sha256:403157f8d3cf86ea5a16c538fbf246a6f04a983c65e7ace78645a8ffa1b14d27
Status: Downloaded newer image for sciapp/nojava-ipmi-kvm:v0.9.0-openjdk-7
[INFO] Starting new HTTPS connection (1): mykvmhost.org
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
[ERROR] Login to https://mykvmhost.org/rpc/WEBSES/create.asp was not successful.
[INFO] Waiting for the Docker container to be up and ready...
[ERROR] Docker terminated with return code 3. Maybe you entered a wrong password?

**Comment by lambq** [comment]
I have successfully run it!

**Comment by lambq** [comment]
Thank you!
