### ISSUE TITLE
I hope Python can start Docker and mount the ISO directory

### ISSUE THREAD

**Issue by lambq** [sciapp/nojava-ipmi-kvm#19]
Thank you! The support of the big shots

**Comment by IngoMeyer441** [comment]
Is this related to #11?

**Comment by lambq** [comment]
![1687788209240](https://github.com/sciapp/nojava-ipmi-kvm/assets/18312530/248780e6-b1db-42a2-a966-c6b5a6b98355)
Regarding this issue, I can try it myself!
