### ISSUE TITLE
nojava-ipmi-kvm-podman requires a modified registries.conf ...

### ISSUE THREAD

**Issue by gardar** [sciapp/nojava-ipmi-kvm#23]
...Since the container is published on dockerhub and by podman by default does not search docker.io

Running `nojava-ipmi-kvm` installed from `nojava-ipmi-kvm-podman` with a clean install of `podman` causes this error:
```
[ERROR] Docker terminated with return code 125.
```

Which is not really descriptive of the issue.

Possible solutions:
  - Source the images from `docker.io/sciapp/nojava-ipmi-kvm` rather than just `sciapp/nojava-ipmi-kvm`
  - print a notice in `post_install` in the aur package.
  - Add the registry during install to `/etc/containers/registries.conf.d/` (probably a bad idea)
  - Publish the containers also to the registries that podman searches by default

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by IngoMeyer441** [comment]
Thanks for your issue report. I think using fully qualified image names is the cleanest solution. I have added the `docker.io` domain in the latest commit on `develop` (624338d4fc735d31ee0ce3d9d5de8c4a202abed9). Could you please test this with the `nojava-ipmi-kvm-podman-git` AUR package?

**Comment by gardar** [comment]
Yes that's excellent, thanks for the quick resolution!
